In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import dataframe_image as dfi

In [15]:
data = pd.read_excel("E:/UCLA/Bruin Sports Analytics/Tennis/Govind Nanda (UCLA) Raphael Perot (Texas A&M) Full Match.xlsx")
data
player_name = "Govind Nanda"

In [28]:
def is_odd(n):
  return n % 2 == 1

def is_even(n):
    return n % 2 == 0

In [30]:
winners_serve = pd.DataFrame(data.loc[(data["isWinner"] == 1) & (data["serverName"] == player_name) & (data["shotInRally"].apply(is_odd))])
winners_return = pd.DataFrame(data.loc[(data["isWinner"] == 1) & (data["serverName"] != player_name) & (data["shotInRally"].apply(is_even))])
winners = pd.concat([winners_return, winners_serve])
winners

,pointScore,gameScore,setScore,isPointStart,PointStartTime,isPointEnd,PointEndTime,shotInRally,serverName,firstServeIn,...,Division,Event,lineupPosition,matchDetails,opponentTeam,player1Name,player2Name,Round,Surface,Notes
27,30-40,0-0,0-0,NaN,NaN,1.0,NaN,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,15-30,2024-01-01 00:00:00,0-0,NaN,NaN,1.0,692658.0,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,40-40 (Deuce),2024-01-01 00:00:00,0-0,NaN,NaN,1.0,833637.0,4.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,40-30,2024-04-02 00:00:00,0-0,NaN,NaN,1.0,2425577.0,4.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,15-0,2024-05-03 00:00:00,0-0,NaN,NaN,1.0,2825333.0,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,15-0,2024-05-05 00:00:00,0-0,NaN,NaN,1.0,3547714.0,2.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,30-40,2024-05-05 00:00:00,0-0,NaN,NaN,1.0,3712619.0,4.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,30-40,2024-01-01 00:00:00,1-0,NaN,NaN,1.0,4884643.0,10.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,15-0,2024-03-01 00:00:00,1-0,NaN,NaN,1.0,5293268.0,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,0-15,2024-05-03 00:00:00,1-0,NaN,NaN,1.0,6388241.0,2.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,15-15,1-0,0-0,NaN,NaN,1.0,NaN,17.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,30-30,1-0,0-0,1.0,447690.0,1.0,453760.0,1.0,Govind Nanda,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,15-0,2024-02-01 00:00:00,0-0,NaN,NaN,1.0,988637.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,30-0,2024-02-01 00:00:00,0-0,NaN,NaN,1.0,1015770.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,0-15,2024-03-02 00:00:00,0-0,1.0,1318506.0,1.0,1322298.0,1.0,Govind Nanda,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,15-15,2024-04-03 00:00:00,0-0,NaN,NaN,1.0,2672716.0,17.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,0-30,2024-05-04 00:00:00,0-0,NaN,NaN,1.0,3264091.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,0-0,2024-06-05 00:00:00,0-0,NaN,NaN,1.0,3830518.0,11.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,40-30,2024-06-05 00:00:00,0-0,NaN,NaN,1.0,4012397.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,0-0,0-1,1-0,NaN,NaN,1.0,4539621.0,17.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,30-0,0-1,1-0,NaN,NaN,1.0,4627667.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,40-0,0-1,1-0,NaN,NaN,1.0,4650210.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,0-0,2024-02-01 00:00:00,1-0,NaN,NaN,1.0,4993653.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,15-30,2024-02-01 00:00:00,1-0,NaN,NaN,1.0,5121482.0,7.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
winner_percent = (len(winners)/len(data))*100
print(winner_percent)

3.418803418803419

In [32]:
winner_fh = winners.loc[winners["shotType"] == "Forehand"]
winner_fh

,pointScore,gameScore,setScore,isPointStart,PointStartTime,isPointEnd,PointEndTime,shotInRally,serverName,firstServeIn,...,Division,Event,lineupPosition,matchDetails,opponentTeam,player1Name,player2Name,Round,Surface,Notes
27,30-40,0-0,0-0,NaN,NaN,1.0,NaN,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,40-30,2024-04-02 00:00:00,0-0,NaN,NaN,1.0,2425577.0,4.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,15-0,2024-05-03 00:00:00,0-0,NaN,NaN,1.0,2825333.0,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,30-40,2024-01-01 00:00:00,1-0,NaN,NaN,1.0,4884643.0,10.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,15-0,2024-03-01 00:00:00,1-0,NaN,NaN,1.0,5293268.0,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,15-15,1-0,0-0,NaN,NaN,1.0,NaN,17.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,15-15,2024-04-03 00:00:00,0-0,NaN,NaN,1.0,2672716.0,17.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,0-30,2024-05-04 00:00:00,0-0,NaN,NaN,1.0,3264091.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,0-0,2024-06-05 00:00:00,0-0,NaN,NaN,1.0,3830518.0,11.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,40-30,2024-06-05 00:00:00,0-0,NaN,NaN,1.0,4012397.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,0-0,0-1,1-0,NaN,NaN,1.0,4539621.0,17.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,30-0,0-1,1-0,NaN,NaN,1.0,4627667.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,40-0,0-1,1-0,NaN,NaN,1.0,4650210.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,15-30,2024-02-01 00:00:00,1-0,NaN,NaN,1.0,5121482.0,7.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
winner_bh = winners.loc[winners["shotType"] == "Backhand"]
winner_bh

,pointScore,gameScore,setScore,isPointStart,PointStartTime,isPointEnd,PointEndTime,shotInRally,serverName,firstServeIn,...,Division,Event,lineupPosition,matchDetails,opponentTeam,player1Name,player2Name,Round,Surface,Notes
97,15-30,2024-01-01 00:00:00,0-0,NaN,NaN,1.0,692658.0,8.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,40-40 (Deuce),2024-01-01 00:00:00,0-0,NaN,NaN,1.0,833637.0,4.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,30-40,2024-05-05 00:00:00,0-0,NaN,NaN,1.0,3712619.0,4.0,Raphael Perot,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,15-0,2024-02-01 00:00:00,0-0,NaN,NaN,1.0,988637.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,30-0,2024-02-01 00:00:00,0-0,NaN,NaN,1.0,1015770.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,0-0,2024-02-01 00:00:00,1-0,NaN,NaN,1.0,4993653.0,5.0,Govind Nanda,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
winner_fh_pct = (len(winner_fh)/len(winners))*100
print(winner_fh_pct)

58.333333333333336

In [35]:
winner_bh_pct = (len(winner_bh)/len(winners))*100
print(winner_bh_pct)

25.0

In [36]:
colours = ['#2D68C4', '#F2AA00']

In [37]:
winner_percent_list = [winner_percent]
plot_data_winner = pd.DataFrame({
    'Category': ['Winners'],
    'Percentage': [winner_percent]
})
plot_data = pd.DataFrame({
    'Shot Type': ['Forehand', 'Backhand'],
    'Percentage': [winner_fh_pct, winner_bh_pct]
})

In [38]:
plot_data_winner

  Category  Percentage
0  Winners    3.418803

In [39]:
plot_data

  Shot Type  Percentage
0  Forehand   58.333333
1  Backhand   25.000000